added ec2 instance
geoffrey1330/trello-tasks pull request #12
Opened 2022-06-11 15:02 UTC by geoffrey1330

2022-06-20 22:47 UTC, vladimirmukhin requested changes

2022-06-20 22:47 UTC, vladimirmukhin commented on instance.tf
> +  count                  = length(local.public_cidr)
no need to use count here

2022-06-20 22:47 UTC, vladimirmukhin commented on instance.tf
> +  count                  = length(local.public_cidr)
no need to use count here

2022-06-20 22:47 UTC, vladimirmukhin commented on instance.tf
> +  ami                    = "ami-0022f774911c1d690"
This will only work in a single region.
If you want to change the region, you'll need to also change the ami id - this is not a scalable solution.

Instead, you can use the feature of terraform which is called data source.

More details here:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami

Examples here:
https://github.com/vladimirmukhin/data_source_example/blob/main/main.tf

2022-06-20 22:47 UTC, vladimirmukhin commented on instance.tf
> +  ami                    = "ami-0022f774911c1d690"
This will only work in a single region.
If you want to change the region, you'll need to also change the ami id - this is not a scalable solution.

Instead, you can use the feature of terraform which is called data source.

More details here:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami

Examples here:
https://github.com/vladimirmukhin/data_source_example/blob/main/main.tf

2022-06-20 22:47 UTC, vladimirmukhin commented on instance.tf
> +  key_name               = "${var.env_code}-keypair"
Please rename it to main. This will allow me to troubleshoot your code more easily if needed in future
```suggestion
  key_name               = "main"
```

2022-06-20 22:47 UTC, vladimirmukhin commented on instance.tf
> +  key_name               = "${var.env_code}-keypair"
Please rename it to main. This will allow me to troubleshoot your code more easily if needed in future
```suggestion
  key_name               = "${var.env_code}-keypair"
```

2022-06-20 22:47 UTC, vladimirmukhin commented on instance.tf
> +}
Please add trailing newline

2022-06-20 22:49 UTC, geoffrey1330 commented on instance.tf
> +  ami                    = "ami-0022f774911c1d690"
OK

2022-06-20 22:50 UTC, geoffrey1330 commented on instance.tf
> +  key_name               = "${var.env_code}-keypair"
OK i will change it to main

2022-06-20 22:51 UTC, geoffrey1330 commented on instance.tf
> +}
OK

2022-06-20 22:52 UTC, geoffrey1330 commented on instance.tf
> +  key_name               = "${var.env_code}-keypair"
main-keypair or just main?

2022-06-21 14:47 UTC, vladimirmukhin requested changes

2022-06-21 14:47 UTC, vladimirmukhin commented on instance.tf
> +  subnet_id              = aws_subnet.public.id
```suggestion
resource "aws_instance" "web_public" {
  ami                    = data.aws_ami.ubuntu.id
  instance_type          = "t2.micro"
  key_name               = "main"
  vpc_security_group_ids = [aws_security_group.web-sg.id]
  subnet_id              = aws_subnet.public.id
```

2022-06-21 14:47 UTC, vladimirmukhin commented on instance.tf
> +}
```suggestion
resource "aws_instance" "web_private" {
  ami                    = data.aws_ami.ubuntu.id
  instance_type          = "t2.micro"
  key_name               = "main"
  vpc_security_group_ids = [aws_security_group.web-sg.id]
  subnet_id              = aws_subnet.private.id

  tags = {
    Name = "${var.env_code}-web"
  }
}
```

2022-06-21 14:47 UTC, vladimirmukhin commented on instance.tf
> +resource "aws_instance" "web_private" {
```suggestion
}

resource "aws_instance" "web_private" {
```

2022-06-21 14:50 UTC, geoffrey1330 commented on instance.tf
> +}
OK

2022-06-21 23:10 UTC, vladimirmukhin commented on instance.tf
> +  key_name               = "${var.env_code}-keypair"
just main

2022-06-21 23:13 UTC, vladimirmukhin requested changes

2022-06-21 23:13 UTC, vladimirmukhin commented on instance.tf
> +  }
You don't yet need port 80
```suggestion
```

2022-06-21 23:13 UTC, vladimirmukhin commented on instance.tf
> +    cidr_blocks = ["0.0.0.0/0"]
Please limit it to the public IP of your ISP

2022-06-21 23:13 UTC, vladimirmukhin commented on instance.tf
> +  egress {
```suggestion
  }
  
  egress {
```

2022-06-21 23:13 UTC, vladimirmukhin commented on instance.tf
> +  ami           = data.aws_ami.amazonlinux.id
```suggestion
resource "aws_instance" "web_public" {
  ami           = data.aws_ami.amazonlinux.id
```

2022-06-21 23:13 UTC, vladimirmukhin commented on instance.tf
> +resource "aws_instance" "web_private" {
```suggestion
}

resource "aws_instance" "web_private" {
```

2022-06-22 15:31 UTC, vladimirmukhin requested changes

2022-06-22 15:31 UTC, vladimirmukhin commented on instance.tf
> +    cidr_blocks = ["10.0.0.0/24", "10.0.1.0/24"]
That's not your ISP address. ISP address is a public IP that is available via the internet. You can learn it from the website like https://whatismyipaddress.com/

2022-06-24 15:05 UTC, vladimirmukhin approved these changes

2022-06-24 15:16 UTC, merged